apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-demo-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-demo-app
    spec:
      containers:
        - name: node-demo-app
          image: kannanplayarea/docker_demo:1.0
          ports:
            - containerPort: 80
